services:
  postgres:
    image: postgres:16
    container_name: mini_dropbox_db
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dropbox
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
